#!/usr/bin/env python2

"""

"""
__author__ = "Martin Simon <martiin.siimon@gmail.com>"

# try to import local files first
try:
        import sys
        path = '../frimm'
        sys.path.append(path)
        module = __import__('window')
        reload(module)
        from window import MainWindow
        del sys.path[-1]
except ImportError:
        from frimm.window import MainWindow

from gi.repository import Gtk

if __name__ == '__main__':
    main = MainWindow()
    Gtk.main()
